import { db, pool } from "./index";
import { exercisesTable, workoutsTable } from "./schema";
import { sql } from "drizzle-orm";

const exercises = [
  // CHEST
  { name: "Barbell Bench Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Classic flat bench press with a barbell." },
  { name: "Incline Barbell Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Upper chest emphasis on incline bench." },
  { name: "Decline Barbell Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Lower chest emphasis on decline bench." },
  { name: "Dumbbell Bench Press", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Greater range of motion than barbell press." },
  { name: "Incline Dumbbell Press", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Incline press with dumbbells for upper chest." },
  { name: "Cable Flye", category: "strength", muscleGroup: "chest", equipment: "cable", description: "Cable crossover isolation for pec stretch." },
  { name: "Dumbbell Flye", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Pec isolation with wide arc motion." },
  { name: "Push-Up", category: "strength", muscleGroup: "chest", equipment: "bodyweight", description: "Classic push-up, compound chest and triceps." },
  { name: "Wide Push-Up", category: "strength", muscleGroup: "chest", equipment: "bodyweight", description: "Wide hand placement for more chest activation." },
  { name: "Pec Deck Machine", category: "strength", muscleGroup: "chest", equipment: "machine", description: "Chest fly isolation on pec deck." },
  { name: "Smith Machine Bench Press", category: "strength", muscleGroup: "chest", equipment: "machine", description: "Bench press on guided Smith machine." },
  { name: "Chest Dip", category: "strength", muscleGroup: "chest", equipment: "bodyweight", description: "Parallel bar dip leaning forward for chest." },
  { name: "Landmine Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Angled press using a landmine attachment." },
  { name: "Svend Press", category: "strength", muscleGroup: "chest", equipment: "other", description: "Plate press with constant pec squeeze." },
  { name: "Cable Low Flye", category: "strength", muscleGroup: "chest", equipment: "cable", description: "Low cable flye hitting upper chest." },
  { name: "Hex Press", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Close-grip dumbbell press squeezing together." },
  // BACK
  { name: "Deadlift", category: "strength", muscleGroup: "back", equipment: "barbell", description: "King of all lifts — full posterior chain." },
  { name: "Romanian Deadlift", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Hip-hinge deadlift targeting hamstrings and lower back." },
  { name: "Barbell Row", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Bent-over row for upper back thickness." },
  { name: "T-Bar Row", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Landmine row for mid-back thickness." },
  { name: "Seated Cable Row", category: "strength", muscleGroup: "back", equipment: "cable", description: "Seated row targeting mid and lower traps." },
  { name: "Lat Pulldown", category: "strength", muscleGroup: "back", equipment: "cable", description: "Wide grip lat pulldown for width." },
  { name: "Close Grip Pulldown", category: "strength", muscleGroup: "back", equipment: "cable", description: "Neutral grip for lower lat focus." },
  { name: "Pull-Up", category: "strength", muscleGroup: "back", equipment: "bodyweight", description: "Wide grip bodyweight pull-up." },
  { name: "Chin-Up", category: "strength", muscleGroup: "back", equipment: "bodyweight", description: "Underhand grip, more bicep involvement." },
  { name: "One-Arm Dumbbell Row", category: "strength", muscleGroup: "back", equipment: "dumbbell", description: "Unilateral row for lat and rhomboid." },
  { name: "Face Pull", category: "strength", muscleGroup: "back", equipment: "cable", description: "Rear delt and external rotation pull." },
  { name: "Good Morning", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Hip hinge with barbell for spinal erectors." },
  { name: "Cable Straight-Arm Pulldown", category: "strength", muscleGroup: "back", equipment: "cable", description: "Isolation for lats with straight arms." },
  { name: "Pendlay Row", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Strict row from the floor each rep." },
  { name: "Rack Pull", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Partial range deadlift from knee height." },
  { name: "Machine Row", category: "strength", muscleGroup: "back", equipment: "machine", description: "Chest-supported row machine." },
  // LEGS
  { name: "Barbell Back Squat", category: "strength", muscleGroup: "legs", equipment: "barbell", description: "King of leg movements. High bar or low bar." },
  { name: "Front Squat", category: "strength", muscleGroup: "legs", equipment: "barbell", description: "Quad-dominant squat with bar in front rack." },
  { name: "Leg Press", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Machine leg press, great for volume." },
  { name: "Hack Squat", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Angled squat machine targeting quads." },
  { name: "Bulgarian Split Squat", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Rear foot elevated split squat." },
  { name: "Leg Extension", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Quad isolation on leg extension machine." },
  { name: "Lying Leg Curl", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Hamstring isolation lying down." },
  { name: "Seated Leg Curl", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Seated hamstring curl machine." },
  { name: "Standing Calf Raise", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Calf raise on standing machine." },
  { name: "Seated Calf Raise", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Seated calf raise targeting soleus." },
  { name: "Dumbbell Romanian Deadlift", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Dumbbell RDL for hamstrings." },
  { name: "Goblet Squat", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Dumbbell goblet squat, great for beginners." },
  { name: "Walking Lunge", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Alternating lunges with dumbbells." },
  { name: "Sumo Squat", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Wide-stance squat for inner thighs and glutes." },
  { name: "Nordic Curl", category: "strength", muscleGroup: "legs", equipment: "bodyweight", description: "Eccentric hamstring dominant exercise." },
  { name: "Hip Thrust", category: "strength", muscleGroup: "legs", equipment: "barbell", description: "Barbell hip thrust for glutes." },
  // SHOULDERS
  { name: "Overhead Press", category: "strength", muscleGroup: "shoulders", equipment: "barbell", description: "Standing barbell press above head." },
  { name: "Seated Dumbbell Press", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Seated overhead press with dumbbells." },
  { name: "Lateral Raise", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Side delt isolation with dumbbells." },
  { name: "Cable Lateral Raise", category: "strength", muscleGroup: "shoulders", equipment: "cable", description: "Side delt isolation with constant tension." },
  { name: "Front Raise", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Anterior delt raise with dumbbells." },
  { name: "Rear Delt Flye", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Bent-over rear delt flye." },
  { name: "Arnold Press", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Rotating dumbbell press developed by Arnold." },
  { name: "Upright Row", category: "strength", muscleGroup: "shoulders", equipment: "barbell", description: "Barbell upright row for side delts and traps." },
  { name: "Machine Shoulder Press", category: "strength", muscleGroup: "shoulders", equipment: "machine", description: "Guided overhead press on a machine." },
  { name: "Cable Face Pull", category: "strength", muscleGroup: "shoulders", equipment: "cable", description: "Face pull for rear delts and external rotation." },
  { name: "Barbell Shrug", category: "strength", muscleGroup: "shoulders", equipment: "barbell", description: "Trap isolation with heavy shrugs." },
  { name: "Dumbbell Shrug", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Trap isolation with dumbbells." },
  // ARMS
  { name: "Barbell Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Classic bicep curl with straight bar." },
  { name: "EZ Bar Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Curl with EZ bar to reduce wrist stress." },
  { name: "Dumbbell Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Alternating or simultaneous dumbbell curls." },
  { name: "Hammer Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Neutral grip curl for brachialis." },
  { name: "Preacher Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Strict curl on preacher bench." },
  { name: "Concentration Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Seated isolation curl for peak contraction." },
  { name: "Cable Curl", category: "strength", muscleGroup: "arms", equipment: "cable", description: "Constant tension bicep curl with cable." },
  { name: "Incline Dumbbell Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Curl on incline bench for full stretch." },
  { name: "Close Grip Bench Press", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Narrow grip bench for tricep focus." },
  { name: "Tricep Pushdown", category: "strength", muscleGroup: "arms", equipment: "cable", description: "Cable pushdown for tricep isolation." },
  { name: "Overhead Tricep Extension", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Dumbbell tricep extension overhead." },
  { name: "Skull Crusher", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Lying tricep extension with EZ bar." },
  { name: "Tricep Dip", category: "strength", muscleGroup: "arms", equipment: "bodyweight", description: "Upright dips with elbows close for triceps." },
  { name: "Tricep Kickback", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Bent-over tricep kickback for full extension." },
  { name: "Rope Pushdown", category: "strength", muscleGroup: "arms", equipment: "cable", description: "Rope attachment for lateral heads of tricep." },
  { name: "Reverse Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Overhand grip curl for brachialis and forearms." },
  // CORE
  { name: "Plank", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Isometric core hold in push-up position." },
  { name: "Side Plank", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Lateral plank for oblique strength." },
  { name: "Crunches", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Classic crunch for rectus abdominis." },
  { name: "Bicycle Crunch", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Rotational crunch for obliques." },
  { name: "Leg Raise", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Hanging or lying leg raise for lower abs." },
  { name: "Cable Crunch", category: "core", muscleGroup: "core", equipment: "cable", description: "Kneeling cable crunch for weighted ab work." },
  { name: "Ab Wheel Rollout", category: "core", muscleGroup: "core", equipment: "other", description: "Full core engagement with ab wheel." },
  { name: "Russian Twist", category: "core", muscleGroup: "core", equipment: "other", description: "Weighted rotational movement for obliques." },
  { name: "Dragon Flag", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Advanced full body core movement." },
  { name: "Pallof Press", category: "core", muscleGroup: "core", equipment: "cable", description: "Anti-rotation cable press for core stability." },
  { name: "Dead Bug", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Controlled core bracing and limb extension." },
  { name: "Hollow Body Hold", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Gymnastic-style posterior pelvic tilt hold." },
  // FULL BODY
  { name: "Thruster", category: "strength", muscleGroup: "full_body", equipment: "barbell", description: "Front squat to push press combination." },
  { name: "Burpee", category: "cardio", muscleGroup: "full_body", equipment: "bodyweight", description: "High-intensity squat thrust movement." },
  { name: "Box Jump", category: "plyometrics", muscleGroup: "full_body", equipment: "other", description: "Explosive jump onto a plyometric box." },
  { name: "Kettlebell Swing", category: "strength", muscleGroup: "full_body", equipment: "kettlebell", description: "Hip-hinge explosive swing with kettlebell." },
  { name: "Kettlebell Clean", category: "strength", muscleGroup: "full_body", equipment: "kettlebell", description: "Single-arm kettlebell clean to rack position." },
  { name: "Turkish Get-Up", category: "strength", muscleGroup: "full_body", equipment: "kettlebell", description: "Multi-step full body stability movement." },
  { name: "Battle Rope Waves", category: "cardio", muscleGroup: "full_body", equipment: "other", description: "Alternating rope waves for conditioning." },
  { name: "Sled Push", category: "cardio", muscleGroup: "full_body", equipment: "other", description: "Pushing a weighted sled for conditioning." },
  { name: "Rowing Machine", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Ergometer rowing for full body cardio." },
  { name: "Jump Rope", category: "cardio", muscleGroup: "full_body", equipment: "other", description: "Skipping rope for cardiovascular endurance." },
  { name: "Mountain Climbers", category: "cardio", muscleGroup: "full_body", equipment: "bodyweight", description: "Alternating knee drives in plank position." },
  { name: "Bear Crawl", category: "cardio", muscleGroup: "full_body", equipment: "bodyweight", description: "Quadrupedal locomotion for conditioning." },
  { name: "Power Clean", category: "olympic", muscleGroup: "full_body", equipment: "barbell", description: "Explosive pull ending in quarter squat." },
  { name: "Treadmill Run", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Running on a treadmill." },
  { name: "Stationary Bike", category: "cardio", muscleGroup: "legs", equipment: "machine", description: "Seated cycling for cardiovascular fitness." },
  { name: "Elliptical", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Low-impact elliptical trainer." },
  { name: "Stair Climber", category: "cardio", muscleGroup: "legs", equipment: "machine", description: "Step mill for glutes and cardio." },
  { name: "Assault Bike", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Air resistance bike for HIIT." },
  { name: "Hip Flexor Stretch", category: "mobility", muscleGroup: "legs", equipment: "bodyweight", description: "Kneeling lunge hip flexor stretch." },
  { name: "Thoracic Extension", category: "mobility", muscleGroup: "back", equipment: "other", description: "T-spine extension over foam roller." },
  { name: "World's Greatest Stretch", category: "mobility", muscleGroup: "full_body", equipment: "bodyweight", description: "Multi-plane mobility drill." },
  { name: "Pigeon Pose", category: "mobility", muscleGroup: "legs", equipment: "bodyweight", description: "Hip opener targeting external rotators." },
  { name: "Cat-Cow", category: "mobility", muscleGroup: "back", equipment: "bodyweight", description: "Spinal flexion and extension on all fours." },
];

const workouts = [
  { name: "Full Body Starter A", description: "Beginner full-body workout for foundational strength.", difficulty: "beginner", estimatedMinutes: 45, category: "strength" },
  { name: "Full Body Starter B", description: "Alternate with Starter A for a 3-day/week program.", difficulty: "beginner", estimatedMinutes: 45, category: "strength" },
  { name: "Bodyweight Basics", description: "No equipment needed. Perfect for beginners at home.", difficulty: "beginner", estimatedMinutes: 30, category: "bodyweight" },
  { name: "Dumbbell Only Beginner", description: "Full body workout using only a pair of dumbbells.", difficulty: "beginner", estimatedMinutes: 40, category: "strength" },
  { name: "Morning Mobility Flow", description: "Gentle 30-minute mobility and flexibility routine.", difficulty: "beginner", estimatedMinutes: 30, category: "mobility" },
  { name: "Beginner Cardio Conditioning", description: "Low intensity cardio intervals for base conditioning.", difficulty: "beginner", estimatedMinutes: 30, category: "cardio" },
  { name: "First Week Strength", description: "Simple intro to compound movements for week 1.", difficulty: "beginner", estimatedMinutes: 40, category: "strength" },
  { name: "Core Foundations", description: "Build a solid core foundation with beginner-friendly moves.", difficulty: "beginner", estimatedMinutes: 25, category: "core" },
  { name: "Upper Body A", description: "Horizontal push/pull emphasis for upper body.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
  { name: "Upper Body B", description: "Vertical push/pull emphasis for upper body.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
  { name: "Lower Body A", description: "Squat-pattern dominant lower body session.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
  { name: "Lower Body B", description: "Hinge-pattern dominant lower body session.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
  { name: "Push Day", description: "Chest, shoulders, and triceps compound and isolation work.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
  { name: "Pull Day", description: "Back, biceps, and rear delts compound and isolation work.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
  { name: "Leg Day", description: "Quad, hamstring, glute, and calf comprehensive session.", difficulty: "intermediate", estimatedMinutes: 65, category: "strength" },
  { name: "Active Recovery", description: "Light movement, foam rolling, and mobility work.", difficulty: "beginner", estimatedMinutes: 30, category: "mobility" },
  { name: "Chest & Triceps Hypertrophy", description: "Volume-focused push session for muscle size.", difficulty: "intermediate", estimatedMinutes: 65, category: "hypertrophy" },
  { name: "Back & Biceps Hypertrophy", description: "High volume pulling session for back width and thickness.", difficulty: "intermediate", estimatedMinutes: 65, category: "hypertrophy" },
  { name: "Shoulder Hypertrophy", description: "All three delt heads with lateral raises and presses.", difficulty: "intermediate", estimatedMinutes: 50, category: "hypertrophy" },
  { name: "Legs Hypertrophy", description: "High volume quad and hamstring session.", difficulty: "intermediate", estimatedMinutes: 70, category: "hypertrophy" },
  { name: "Arm Specialization", description: "Dedicated bicep and tricep volume day.", difficulty: "intermediate", estimatedMinutes: 45, category: "hypertrophy" },
  { name: "Chest Specialization", description: "High volume chest with multiple angles and tempos.", difficulty: "intermediate", estimatedMinutes: 60, category: "hypertrophy" },
  { name: "Back Specialization", description: "Thickness and width focus with heavy rows and pulldowns.", difficulty: "intermediate", estimatedMinutes: 60, category: "hypertrophy" },
  { name: "Glute Focus", description: "Glute-dominant lower body session.", difficulty: "intermediate", estimatedMinutes: 55, category: "hypertrophy" },
  { name: "Squat Day (Strength)", description: "Squat-focused strength session with accessory work.", difficulty: "advanced", estimatedMinutes: 75, category: "powerlifting" },
  { name: "Bench Day (Strength)", description: "Bench press-focused session with tricep accessories.", difficulty: "advanced", estimatedMinutes: 70, category: "powerlifting" },
  { name: "Deadlift Day (Strength)", description: "Deadlift main lift with back accessories.", difficulty: "advanced", estimatedMinutes: 70, category: "powerlifting" },
  { name: "OHP Day (Strength)", description: "Overhead press as main movement.", difficulty: "advanced", estimatedMinutes: 65, category: "powerlifting" },
  { name: "5x5 Workout A", description: "StrongLifts 5x5 Workout A pattern.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
  { name: "5x5 Workout B", description: "StrongLifts 5x5 Workout B pattern.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
  { name: "Heavy Singles Day", description: "Max effort day working up to heavy singles.", difficulty: "advanced", estimatedMinutes: 80, category: "powerlifting" },
  { name: "Deload Week Workout", description: "Reduced intensity for recovery and adaptation.", difficulty: "beginner", estimatedMinutes: 40, category: "strength" },
  { name: "HIIT Circuit A", description: "High intensity interval training with bodyweight and kettlebells.", difficulty: "intermediate", estimatedMinutes: 35, category: "cardio" },
  { name: "HIIT Circuit B", description: "Metabolic conditioning circuit for fat loss.", difficulty: "intermediate", estimatedMinutes: 35, category: "cardio" },
  { name: "Athletic Power Development", description: "Box jumps, cleans, and explosive movements.", difficulty: "advanced", estimatedMinutes: 60, category: "athletic" },
  { name: "Kettlebell Conditioning", description: "Swings, cleans, snatches for full body conditioning.", difficulty: "intermediate", estimatedMinutes: 45, category: "conditioning" },
  { name: "Sprint Intervals", description: "Treadmill sprint intervals for speed and conditioning.", difficulty: "advanced", estimatedMinutes: 30, category: "cardio" },
  { name: "Functional Fitness", description: "Compound movements mimicking real-world patterns.", difficulty: "intermediate", estimatedMinutes: 50, category: "functional" },
  { name: "CrossFit-Style WOD", description: "Mixed modal workout combining strength and cardio.", difficulty: "advanced", estimatedMinutes: 40, category: "conditioning" },
  { name: "Advanced Push Day", description: "High-frequency heavy push with intensity techniques.", difficulty: "advanced", estimatedMinutes: 75, category: "strength" },
  { name: "Advanced Pull Day", description: "Heavy rowing and pulling with accessory volume.", difficulty: "advanced", estimatedMinutes: 75, category: "strength" },
  { name: "Advanced Leg Day", description: "Squat, hinge, and single-leg work at high intensity.", difficulty: "advanced", estimatedMinutes: 80, category: "strength" },
  { name: "Olympic Lifting Session", description: "Power clean and overhead work.", difficulty: "advanced", estimatedMinutes: 75, category: "olympic" },
  { name: "Bodybuilding Chest Day", description: "Pre-exhaust techniques and high rep finishers.", difficulty: "advanced", estimatedMinutes: 70, category: "hypertrophy" },
  { name: "Mass Building Back Day", description: "Deadlifts, rows, and pulldowns for maximum back mass.", difficulty: "advanced", estimatedMinutes: 75, category: "hypertrophy" },
  { name: "Advanced Core & Abs", description: "Weighted core work, planks, and rotational strength.", difficulty: "advanced", estimatedMinutes: 40, category: "core" },
  { name: "Peak Week Pump Session", description: "Light weight, high rep pump work.", difficulty: "intermediate", estimatedMinutes: 50, category: "hypertrophy" },
  { name: "Mobility & Stretching", description: "Comprehensive flexibility and mobility session.", difficulty: "beginner", estimatedMinutes: 60, category: "mobility" },
  { name: "Posterior Chain Focus", description: "Deadlift, RDL, hamstring curls, and back extensions.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
  { name: "Core Stability Advanced", description: "Anti-rotation, anti-flexion, and stability challenges.", difficulty: "advanced", estimatedMinutes: 40, category: "core" },
  { name: "Shoulder Rehab & Prehab", description: "Rotator cuff strengthening and mobility.", difficulty: "beginner", estimatedMinutes: 30, category: "mobility" },
  { name: "Grip & Forearm Strength", description: "Wrist curls, farmer's carries, and plate pinches.", difficulty: "intermediate", estimatedMinutes: 25, category: "strength" },
  { name: "Mindful Yoga Flow", description: "Strength yoga blending flexibility with bodyweight resistance.", difficulty: "beginner", estimatedMinutes: 45, category: "yoga" },
  { name: "Boxing Conditioning", description: "Shadow boxing, bag work, and footwork drills.", difficulty: "intermediate", estimatedMinutes: 45, category: "cardio" },
];

async function main() {
  console.log("🌱 Clearing old workout exercises and logs...");
  await db.execute(sql`TRUNCATE TABLE workout_exercises CASCADE`);
  await db.execute(sql`DELETE FROM exercises WHERE is_custom = false`);

  console.log("🌱 Seeding exercises...");
  for (const e of exercises) {
    await db.insert(exercisesTable).values({
      name: e.name,
      description: e.description,
      category: e.category,
      muscleGroup: e.muscleGroup,
      equipment: e.equipment,
      isCustom: false,
    }).onConflictDoNothing();
  }
  console.log(`✅ ${exercises.length} exercises seeded`);

  console.log("🌱 Seeding workout plans...");
  for (const w of workouts) {
    await db.insert(workoutsTable).values({
      name: w.name,
      description: w.description,
      difficulty: w.difficulty,
      estimatedMinutes: w.estimatedMinutes,
      category: w.category,
      isAiGenerated: false,
    }).onConflictDoNothing();
  }
  console.log(`✅ ${workouts.length} workout plans seeded`);

  await pool.end();
  console.log("🎉 Seed complete!");
}

main().catch((e) => { console.error(e); process.exit(1); });
