import { db, pool } from "./index";
import { exercisesTable, workoutsTable, workoutExercisesTable } from "./schema";
import { sql, eq } from "drizzle-orm";

const exercises = [
  // CHEST
  { name: "Barbell Bench Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Classic flat bench press with a barbell.", instructions: "1. Lie flat on bench, eyes under the bar\n2. Grip bar slightly wider than shoulder-width\n3. Unrack and lower bar to mid-chest with control\n4. Press up explosively to lockout\n5. Keep feet flat, natural arch in lower back" },
  { name: "Incline Barbell Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Upper chest emphasis on incline bench.", instructions: "1. Set bench to 30–45° incline\n2. Grip bar slightly wider than shoulder-width\n3. Lower bar to upper chest\n4. Press up and slightly back toward the rack\n5. Keep shoulders retracted throughout" },
  { name: "Decline Barbell Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Lower chest emphasis on decline bench.", instructions: "1. Secure feet on decline bench\n2. Grip bar at shoulder-width\n3. Lower bar to lower chest\n4. Press up to full extension\n5. Control the descent to avoid shoulder strain" },
  { name: "Dumbbell Bench Press", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Greater range of motion than barbell press.", instructions: "1. Lie flat, hold dumbbells at chest level\n2. Press up and slightly together at the top\n3. Lower with elbows at ~75° from torso\n4. Full stretch at bottom, squeeze at top\n5. Neutral wrist throughout" },
  { name: "Incline Dumbbell Press", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Incline press with dumbbells for upper chest.", instructions: "1. Set bench to 30–45°\n2. Press dumbbells from upper chest\n3. Arc them slightly together at top\n4. Feel the upper pec stretch at the bottom\n5. Don't flare elbows excessively" },
  { name: "Cable Flye", category: "strength", muscleGroup: "chest", equipment: "cable", description: "Cable crossover isolation for pec stretch.", instructions: "1. Stand between two high cable pulleys\n2. Start with arms wide and slightly forward\n3. Bring hands together in a hugging arc\n4. Squeeze pecs hard at the midpoint\n5. Slowly return under control" },
  { name: "Dumbbell Flye", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Pec isolation with wide arc motion.", instructions: "1. Lie flat, hold dumbbells above chest with slight elbow bend\n2. Lower arms in a wide arc until you feel a deep pec stretch\n3. Reverse the arc to bring dumbbells back together\n4. Keep elbows soft — not a press\n5. Focus on the squeeze at the top" },
  { name: "Push-Up", category: "strength", muscleGroup: "chest", equipment: "bodyweight", description: "Classic push-up, compound chest and triceps.", instructions: "1. Start in plank position, hands slightly wider than shoulder-width\n2. Lower chest toward floor keeping body rigid\n3. Push up to full arm extension\n4. Keep core braced and hips level throughout\n5. Breathe out on the push up" },
  { name: "Wide Push-Up", category: "strength", muscleGroup: "chest", equipment: "bodyweight", description: "Wide hand placement for more chest activation." },
  { name: "Pec Deck Machine", category: "strength", muscleGroup: "chest", equipment: "machine", description: "Chest fly isolation on pec deck.", instructions: "1. Adjust seat so handles align with mid-chest\n2. Place forearms on pads or grip handles\n3. Bring arms together in front of chest\n4. Squeeze pecs at peak contraction\n5. Return slowly without letting weight stack touch" },
  { name: "Smith Machine Bench Press", category: "strength", muscleGroup: "chest", equipment: "machine", description: "Bench press on guided Smith machine." },
  { name: "Chest Dip", category: "strength", muscleGroup: "chest", equipment: "bodyweight", description: "Parallel bar dip leaning forward for chest.", instructions: "1. Grip parallel bars, lean torso forward\n2. Lower until upper arms are parallel to floor\n3. Press up to extension, maintain forward lean\n4. Cross feet behind for stability\n5. Avoid shrugging shoulders" },
  { name: "Landmine Press", category: "strength", muscleGroup: "chest", equipment: "barbell", description: "Angled press using a landmine attachment." },
  { name: "Svend Press", category: "strength", muscleGroup: "chest", equipment: "other", description: "Plate press with constant pec squeeze." },
  { name: "Cable Low Flye", category: "strength", muscleGroup: "chest", equipment: "cable", description: "Low cable flye hitting upper chest." },
  { name: "Hex Press", category: "strength", muscleGroup: "chest", equipment: "dumbbell", description: "Close-grip dumbbell press squeezing together." },
  // BACK
  { name: "Deadlift", category: "strength", muscleGroup: "back", equipment: "barbell", description: "King of all lifts — full posterior chain.", instructions: "1. Stand with bar over mid-foot, hip-width stance\n2. Grip bar just outside legs, hinge and grab\n3. Take slack out of bar, create tension\n4. Push floor away as you lift, keep bar close\n5. Lock out hips at top, reverse to lower\n6. Neutral spine throughout — never round" },
  { name: "Romanian Deadlift", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Hip-hinge deadlift targeting hamstrings and lower back.", instructions: "1. Stand holding bar at hip level\n2. Push hips back, lower bar along legs\n3. Feel hamstring stretch at bottom\n4. Drive hips forward to stand\n5. Keep back flat and bar close to body" },
  { name: "Barbell Row", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Bent-over row for upper back thickness.", instructions: "1. Hinge forward until torso is ~45°\n2. Grip bar just outside hip-width\n3. Pull bar to lower sternum/upper abdomen\n4. Lead with elbows, squeeze shoulder blades\n5. Lower under control — don't jerk" },
  { name: "T-Bar Row", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Landmine row for mid-back thickness.", instructions: "1. Straddle bar, hinge forward\n2. Grip V-handle or use towel around bar\n3. Pull bar to chest/sternum\n4. Squeeze rhomboids at top\n5. Control the descent" },
  { name: "Seated Cable Row", category: "strength", muscleGroup: "back", equipment: "cable", description: "Seated row targeting mid and lower traps.", instructions: "1. Sit upright, feet on footplate\n2. Grab V-bar or handle, lean slightly back\n3. Pull handle to lower sternum\n4. Drive elbows back, squeeze shoulder blades\n5. Lean forward slightly to stretch lats at start" },
  { name: "Lat Pulldown", category: "strength", muscleGroup: "back", equipment: "cable", description: "Wide grip lat pulldown for width.", instructions: "1. Grip bar wider than shoulder-width\n2. Sit, secure thighs under pad\n3. Lean back slightly, arch upper back\n4. Pull bar to upper chest, lead with elbows\n5. Feel lats stretch fully at top of each rep" },
  { name: "Close Grip Pulldown", category: "strength", muscleGroup: "back", equipment: "cable", description: "Neutral grip for lower lat focus." },
  { name: "Pull-Up", category: "strength", muscleGroup: "back", equipment: "bodyweight", description: "Wide grip bodyweight pull-up.", instructions: "1. Hang from bar with overhand grip, wider than shoulder-width\n2. Depress and retract shoulder blades\n3. Pull chest toward bar, lead with elbows\n4. Lower fully to dead hang between reps\n5. Avoid kipping or excessive swinging" },
  { name: "Chin-Up", category: "strength", muscleGroup: "back", equipment: "bodyweight", description: "Underhand grip, more bicep involvement.", instructions: "1. Hang with underhand grip, shoulder-width\n2. Pull chest to bar, lead with elbows\n3. Squeeze biceps and lats at top\n4. Lower with control to full hang\n5. Keep core tight throughout" },
  { name: "One-Arm Dumbbell Row", category: "strength", muscleGroup: "back", equipment: "dumbbell", description: "Unilateral row for lat and rhomboid.", instructions: "1. Place knee and hand on bench for support\n2. Grip dumbbell, arm hanging straight down\n3. Pull elbow toward ceiling, rotating slightly\n4. Squeeze lat at peak\n5. Lower fully without rotating torso excessively" },
  { name: "Face Pull", category: "strength", muscleGroup: "back", equipment: "cable", description: "Rear delt and external rotation pull.", instructions: "1. Set cable to eye level with rope attachment\n2. Grip rope ends, step back\n3. Pull rope to face, splitting the rope at the end\n4. Externally rotate wrists (thumbs back)\n5. Squeeze rear delts and traps" },
  { name: "Good Morning", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Hip hinge with barbell for spinal erectors." },
  { name: "Cable Straight-Arm Pulldown", category: "strength", muscleGroup: "back", equipment: "cable", description: "Isolation for lats with straight arms." },
  { name: "Pendlay Row", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Strict row from the floor each rep." },
  { name: "Rack Pull", category: "strength", muscleGroup: "back", equipment: "barbell", description: "Partial range deadlift from knee height.", instructions: "1. Set safety bars at knee height\n2. Grip bar and create tension same as deadlift\n3. Drive through hips to lock out\n4. Control back to pins\n5. Great for heavy overload and grip work" },
  { name: "Machine Row", category: "strength", muscleGroup: "back", equipment: "machine", description: "Chest-supported row machine." },
  // LEGS
  { name: "Barbell Back Squat", category: "strength", muscleGroup: "legs", equipment: "barbell", description: "King of leg movements. High bar or low bar.", instructions: "1. Bar on upper traps (high bar) or rear delts (low bar)\n2. Stance slightly wider than shoulder-width, toes out ~30°\n3. Break at hips and knees simultaneously\n4. Squat until hips are at or below parallel\n5. Drive knees out and press through full foot\n6. Stand tall, keep chest up throughout" },
  { name: "Front Squat", category: "strength", muscleGroup: "legs", equipment: "barbell", description: "Quad-dominant squat with bar in front rack.", instructions: "1. Rest bar on front delts in clean rack position\n2. Elbows high, upper arms parallel to floor\n3. Feet shoulder-width, toes out slightly\n4. Squat to depth with upright torso\n5. Drive up keeping elbows elevated" },
  { name: "Leg Press", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Machine leg press, great for volume.", instructions: "1. Seat back fully supported, feet on platform\n2. Place feet shoulder-width, mid-to-high platform\n3. Lower platform until knees near 90°\n4. Press through full foot to extension (don't lock out)\n5. Control the descent" },
  { name: "Hack Squat", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Angled squat machine targeting quads." },
  { name: "Bulgarian Split Squat", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Rear foot elevated split squat.", instructions: "1. Place rear foot on bench ~knee height\n2. Front foot far enough out to allow vertical shin\n3. Lower rear knee toward floor\n4. Keep front shin vertical\n5. Drive through front heel to stand\n6. Keep torso upright throughout" },
  { name: "Leg Extension", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Quad isolation on leg extension machine.", instructions: "1. Adjust pad to sit just above ankle\n2. Sit with back against pad, thighs supported\n3. Extend legs to straight\n4. Squeeze quads hard at top\n5. Lower under control — 3 seconds down" },
  { name: "Lying Leg Curl", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Hamstring isolation lying down.", instructions: "1. Lie face down, pad above heels\n2. Curl heels toward glutes\n3. Squeeze hamstrings at peak\n4. Lower slowly — don't let hips rise\n5. Full range of motion for best results" },
  { name: "Seated Leg Curl", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Seated hamstring curl machine." },
  { name: "Standing Calf Raise", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Calf raise on standing machine.", instructions: "1. Place balls of feet on edge of platform\n2. Full stretch at bottom (heels below platform)\n3. Rise up as high as possible\n4. Squeeze calves at top\n5. 2-second pause at top, 3-second descent" },
  { name: "Seated Calf Raise", category: "strength", muscleGroup: "legs", equipment: "machine", description: "Seated calf raise targeting soleus." },
  { name: "Dumbbell Romanian Deadlift", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Dumbbell RDL for hamstrings." },
  { name: "Goblet Squat", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Dumbbell goblet squat, great for beginners.", instructions: "1. Hold dumbbell vertically at chest\n2. Feet shoulder-width, toes out slightly\n3. Squat deep, elbows tracking inside knees\n4. Keep chest up and heels on floor\n5. Press through full foot to stand" },
  { name: "Walking Lunge", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Alternating lunges with dumbbells." },
  { name: "Sumo Squat", category: "strength", muscleGroup: "legs", equipment: "dumbbell", description: "Wide-stance squat for inner thighs and glutes." },
  { name: "Nordic Curl", category: "strength", muscleGroup: "legs", equipment: "bodyweight", description: "Eccentric hamstring dominant exercise.", instructions: "1. Kneel with feet anchored\n2. Keep body rigid from knees to shoulders\n3. Lower torso toward floor as slowly as possible\n4. Use hands to catch yourself at bottom\n5. Hamstring strength controls the descent" },
  { name: "Hip Thrust", category: "strength", muscleGroup: "legs", equipment: "barbell", description: "Barbell hip thrust for glutes.", instructions: "1. Upper back on bench, bar across hips with pad\n2. Feet flat on floor, hip-width\n3. Drive hips up by squeezing glutes\n4. Body forms straight line at top\n5. Lower under control, don't touch floor between reps" },
  // SHOULDERS
  { name: "Overhead Press", category: "strength", muscleGroup: "shoulders", equipment: "barbell", description: "Standing barbell press above head.", instructions: "1. Grip bar just outside shoulder-width\n2. Bar rests on front delts, elbows slightly forward\n3. Press bar straight up, move head back slightly\n4. Fully lock out overhead\n5. Lower to chin level — keep tight throughout" },
  { name: "Seated Dumbbell Press", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Seated overhead press with dumbbells.", instructions: "1. Sit upright, back supported\n2. Hold dumbbells at ear level, elbows out\n3. Press overhead until arms nearly straight\n4. Lower slowly to starting position\n5. Avoid arching lower back excessively" },
  { name: "Lateral Raise", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Side delt isolation with dumbbells.", instructions: "1. Hold dumbbells at sides, slight elbow bend\n2. Raise arms out to sides to shoulder height\n3. Lead with elbows, not wrists\n4. Pause briefly at top\n5. Lower slowly over 3 seconds" },
  { name: "Cable Lateral Raise", category: "strength", muscleGroup: "shoulders", equipment: "cable", description: "Side delt isolation with constant tension.", instructions: "1. Set cable to low position\n2. Stand to side of cable, grab handle with far hand\n3. Raise arm to shoulder height\n4. Constant tension throughout range\n5. Lower with control" },
  { name: "Front Raise", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Anterior delt raise with dumbbells." },
  { name: "Rear Delt Flye", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Bent-over rear delt flye.", instructions: "1. Hinge forward, back flat, chest over floor\n2. Hold dumbbells hanging with soft elbows\n3. Raise arms out to sides, leading with elbows\n4. Squeeze rear delts at top\n5. Don't use momentum — very strict form" },
  { name: "Arnold Press", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Rotating dumbbell press developed by Arnold.", instructions: "1. Start with dumbbells at chin, palms facing you\n2. Rotate palms outward as you press up\n3. Fully extend overhead\n4. Reverse rotation on the way down\n5. Smooth, controlled rotation throughout" },
  { name: "Upright Row", category: "strength", muscleGroup: "shoulders", equipment: "barbell", description: "Barbell upright row for side delts and traps." },
  { name: "Machine Shoulder Press", category: "strength", muscleGroup: "shoulders", equipment: "machine", description: "Guided overhead press on a machine." },
  { name: "Cable Face Pull", category: "strength", muscleGroup: "shoulders", equipment: "cable", description: "Face pull for rear delts and external rotation." },
  { name: "Barbell Shrug", category: "strength", muscleGroup: "shoulders", equipment: "barbell", description: "Trap isolation with heavy shrugs.", instructions: "1. Stand holding bar with overhand grip at thighs\n2. Shrug shoulders straight up toward ears\n3. Hold at top for 1 second\n4. Lower under control\n5. No rolling of shoulders" },
  { name: "Dumbbell Shrug", category: "strength", muscleGroup: "shoulders", equipment: "dumbbell", description: "Trap isolation with dumbbells." },
  // ARMS
  { name: "Barbell Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Classic bicep curl with straight bar.", instructions: "1. Stand with bar at hip level, shoulder-width grip\n2. Keep elbows pinned to sides\n3. Curl bar to shoulder height\n4. Squeeze biceps hard at top\n5. Lower slowly over 3 seconds" },
  { name: "EZ Bar Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Curl with EZ bar to reduce wrist stress." },
  { name: "Dumbbell Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Alternating or simultaneous dumbbell curls.", instructions: "1. Stand with dumbbells at sides, palms forward\n2. Curl one or both up to shoulder height\n3. Supinate wrist at top (turn palm up more)\n4. Squeeze bicep at peak\n5. Lower fully for complete stretch" },
  { name: "Hammer Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Neutral grip curl for brachialis.", instructions: "1. Hold dumbbells with neutral grip (palms facing each other)\n2. Curl up keeping palms facing in\n3. Squeeze brachialis and brachioradialis at top\n4. Lower with control\n5. Great for forearm and bicep thickness" },
  { name: "Preacher Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Strict curl on preacher bench." },
  { name: "Concentration Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Seated isolation curl for peak contraction." },
  { name: "Cable Curl", category: "strength", muscleGroup: "arms", equipment: "cable", description: "Constant tension bicep curl with cable." },
  { name: "Incline Dumbbell Curl", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Curl on incline bench for full stretch." },
  { name: "Close Grip Bench Press", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Narrow grip bench for tricep focus.", instructions: "1. Grip bar shoulder-width or slightly narrower\n2. Lower to lower chest keeping elbows close\n3. Press up to full extension\n4. Feel the triceps working at top\n5. Don't go too narrow — risks wrist strain" },
  { name: "Tricep Pushdown", category: "strength", muscleGroup: "arms", equipment: "cable", description: "Cable pushdown for tricep isolation.", instructions: "1. Set cable to high position with straight bar or rope\n2. Stand close, elbows tucked to sides\n3. Push bar down to full extension\n4. Squeeze triceps at bottom\n5. Let forearms rise to 90° at top — full stretch" },
  { name: "Overhead Tricep Extension", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Dumbbell tricep extension overhead.", instructions: "1. Hold one dumbbell with both hands overhead\n2. Lower behind head by bending elbows\n3. Feel long head of tricep stretch fully\n4. Press up to full extension overhead\n5. Keep upper arms stationary" },
  { name: "Skull Crusher", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Lying tricep extension with EZ bar.", instructions: "1. Lie on bench, hold EZ bar above chest\n2. Lower bar toward forehead by bending elbows only\n3. Reverse at the bottom — press back up\n4. Keep upper arms perpendicular to floor\n5. Control the weight — don't let it slip" },
  { name: "Tricep Dip", category: "strength", muscleGroup: "arms", equipment: "bodyweight", description: "Upright dips with elbows close for triceps." },
  { name: "Tricep Kickback", category: "strength", muscleGroup: "arms", equipment: "dumbbell", description: "Bent-over tricep kickback for full extension." },
  { name: "Rope Pushdown", category: "strength", muscleGroup: "arms", equipment: "cable", description: "Rope attachment for lateral heads of tricep." },
  { name: "Reverse Curl", category: "strength", muscleGroup: "arms", equipment: "barbell", description: "Overhand grip curl for brachialis and forearms." },
  // CORE
  { name: "Plank", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Isometric core hold in push-up position.", instructions: "1. Forearms on ground, elbows under shoulders\n2. Extend legs straight, toes on floor\n3. Maintain straight line from head to heels\n4. Brace abs as if about to be punched\n5. Don't let hips sag or pike up\n6. Breathe steadily throughout" },
  { name: "Side Plank", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Lateral plank for oblique strength.", instructions: "1. Lie on side, forearm on ground under shoulder\n2. Stack feet, lift hips off floor\n3. Form straight line from head to feet\n4. Top hand on hip or extended overhead\n5. Hold position, keep breathing" },
  { name: "Crunches", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Classic crunch for rectus abdominis.", instructions: "1. Lie on back, knees bent, feet flat\n2. Hands behind head (don't pull neck)\n3. Curl upper back off floor using abs\n4. Squeeze at top — only upper back rises\n5. Lower with control — don't release tension" },
  { name: "Bicycle Crunch", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Rotational crunch for obliques.", instructions: "1. Lie on back, hands behind head, legs raised\n2. Bring opposite elbow to opposite knee\n3. Fully extend the other leg\n4. Alternate sides in a cycling motion\n5. Don't pull neck — rotate from torso" },
  { name: "Leg Raise", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Hanging or lying leg raise for lower abs.", instructions: "1. Hang from bar or lie flat on bench\n2. Keep legs straight or slightly bent\n3. Raise legs to 90° or until hips flex\n4. Lower slowly — don't swing\n5. Avoid arching lower back on descent" },
  { name: "Cable Crunch", category: "core", muscleGroup: "core", equipment: "cable", description: "Kneeling cable crunch for weighted ab work.", instructions: "1. Kneel below cable machine with rope attachment\n2. Hold rope by head, don't pull with arms\n3. Crunch down, rounding spine\n4. Feel abs contract at bottom\n5. Return to start — resist cable on way up" },
  { name: "Ab Wheel Rollout", category: "core", muscleGroup: "core", equipment: "other", description: "Full core engagement with ab wheel.", instructions: "1. Kneel, grip ab wheel with both hands\n2. Roll forward slowly until arms nearly extended\n3. Contract abs hard to pull wheel back\n4. Don't let hips drop or back arch\n5. Start with partial range until strong enough" },
  { name: "Russian Twist", category: "core", muscleGroup: "core", equipment: "other", description: "Weighted rotational movement for obliques.", instructions: "1. Sit with hips bent, feet slightly off floor\n2. Hold weight or clasp hands in front\n3. Rotate torso side to side\n4. Touch weight to floor on each side\n5. Keep core braced throughout" },
  { name: "Dragon Flag", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Advanced full body core movement." },
  { name: "Pallof Press", category: "core", muscleGroup: "core", equipment: "cable", description: "Anti-rotation cable press for core stability.", instructions: "1. Stand sideways to cable at chest height\n2. Hold handle at chest with both hands\n3. Press arms straight out — resist rotating\n4. Hold 2 seconds, return\n5. The goal is NO rotation — pure stability" },
  { name: "Dead Bug", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Controlled core bracing and limb extension.", instructions: "1. Lie on back, arms up, knees bent 90° in air\n2. Brace core — flatten lower back to floor\n3. Slowly lower opposite arm and leg toward floor\n4. Return to start without losing core brace\n5. Breathe out as you lower limbs" },
  { name: "Hollow Body Hold", category: "core", muscleGroup: "core", equipment: "bodyweight", description: "Gymnastic-style posterior pelvic tilt hold." },
  // FULL BODY
  { name: "Thruster", category: "strength", muscleGroup: "full_body", equipment: "barbell", description: "Front squat to push press combination.", instructions: "1. Hold bar in front rack\n2. Squat to full depth\n3. As you stand, use momentum to press bar overhead\n4. Lock out arms at top\n5. Lower bar back to front rack and repeat" },
  { name: "Burpee", category: "cardio", muscleGroup: "full_body", equipment: "bodyweight", description: "High-intensity squat thrust movement.", instructions: "1. Stand, drop hands to floor\n2. Jump or step feet back to plank\n3. Perform a push-up (optional)\n4. Jump feet to hands\n5. Explosively jump up with arms overhead" },
  { name: "Box Jump", category: "plyometrics", muscleGroup: "full_body", equipment: "other", description: "Explosive jump onto a plyometric box.", instructions: "1. Stand arms-length from box\n2. Bend knees, swing arms back\n3. Explode upward and forward\n4. Land softly with bent knees on box\n5. Step down — don't jump down" },
  { name: "Kettlebell Swing", category: "strength", muscleGroup: "full_body", equipment: "kettlebell", description: "Hip-hinge explosive swing with kettlebell.", instructions: "1. Hinge at hips, grip kettlebell with both hands\n2. Hike it back between legs\n3. Drive hips forward explosively\n4. Let kettlebell float to chest height\n5. Hinge back again — the power comes from the hips, not arms" },
  { name: "Kettlebell Clean", category: "strength", muscleGroup: "full_body", equipment: "kettlebell", description: "Single-arm kettlebell clean to rack position." },
  { name: "Turkish Get-Up", category: "strength", muscleGroup: "full_body", equipment: "kettlebell", description: "Multi-step full body stability movement." },
  { name: "Battle Rope Waves", category: "cardio", muscleGroup: "full_body", equipment: "other", description: "Alternating rope waves for conditioning." },
  { name: "Sled Push", category: "cardio", muscleGroup: "full_body", equipment: "other", description: "Pushing a weighted sled for conditioning." },
  { name: "Rowing Machine", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Ergometer rowing for full body cardio.", instructions: "1. Sit with feet strapped in, knees bent\n2. Grab handle with overhand grip\n3. Drive legs first, lean back slightly, then pull arms\n4. Return: arms first, lean forward, then bend knees\n5. Maintain smooth rhythm — legs are the engine" },
  { name: "Jump Rope", category: "cardio", muscleGroup: "full_body", equipment: "other", description: "Skipping rope for cardiovascular endurance." },
  { name: "Mountain Climbers", category: "cardio", muscleGroup: "full_body", equipment: "bodyweight", description: "Alternating knee drives in plank position.", instructions: "1. Start in high plank, hands under shoulders\n2. Drive one knee toward chest\n3. Switch legs rapidly in alternating fashion\n4. Keep hips level — don't pike up\n5. Move as fast as form allows" },
  { name: "Bear Crawl", category: "cardio", muscleGroup: "full_body", equipment: "bodyweight", description: "Quadrupedal locomotion for conditioning." },
  { name: "Power Clean", category: "olympic", muscleGroup: "full_body", equipment: "barbell", description: "Explosive pull ending in quarter squat.", instructions: "1. Start as a deadlift with bar over mid-foot\n2. Pull explosively, extend hips and knees fast\n3. Shrug and pull elbows high and around\n4. Drop into quarter squat to catch in front rack\n5. Stand to complete the lift" },
  { name: "Treadmill Run", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Running on a treadmill." },
  { name: "Stationary Bike", category: "cardio", muscleGroup: "legs", equipment: "machine", description: "Seated cycling for cardiovascular fitness." },
  { name: "Elliptical", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Low-impact elliptical trainer." },
  { name: "Stair Climber", category: "cardio", muscleGroup: "legs", equipment: "machine", description: "Step mill for glutes and cardio." },
  { name: "Assault Bike", category: "cardio", muscleGroup: "full_body", equipment: "machine", description: "Air resistance bike for HIIT." },
  { name: "Hip Flexor Stretch", category: "mobility", muscleGroup: "legs", equipment: "bodyweight", description: "Kneeling lunge hip flexor stretch." },
  { name: "Thoracic Extension", category: "mobility", muscleGroup: "back", equipment: "other", description: "T-spine extension over foam roller." },
  { name: "World's Greatest Stretch", category: "mobility", muscleGroup: "full_body", equipment: "bodyweight", description: "Multi-plane mobility drill." },
  { name: "Pigeon Pose", category: "mobility", muscleGroup: "legs", equipment: "bodyweight", description: "Hip opener targeting external rotators." },
  { name: "Cat-Cow", category: "mobility", muscleGroup: "back", equipment: "bodyweight", description: "Spinal flexion and extension on all fours." },
];

type WorkoutExerciseDef = { name: string; sets: number; reps: number; restSeconds: number; orderIndex: number };

const workoutExerciseMap: Record<string, WorkoutExerciseDef[]> = {
  "Full Body Starter A": [
    { name: "Barbell Back Squat", sets: 3, reps: 8, restSeconds: 120, orderIndex: 0 },
    { name: "Barbell Bench Press", sets: 3, reps: 8, restSeconds: 90, orderIndex: 1 },
    { name: "Barbell Row", sets: 3, reps: 8, restSeconds: 90, orderIndex: 2 },
    { name: "Overhead Press", sets: 3, reps: 8, restSeconds: 90, orderIndex: 3 },
    { name: "Romanian Deadlift", sets: 3, reps: 10, restSeconds: 90, orderIndex: 4 },
    { name: "Plank", sets: 3, reps: 30, restSeconds: 60, orderIndex: 5 },
  ],
  "Full Body Starter B": [
    { name: "Leg Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 0 },
    { name: "Dumbbell Bench Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 1 },
    { name: "Lat Pulldown", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Seated Dumbbell Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 3 },
    { name: "Goblet Squat", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Dead Bug", sets: 3, reps: 10, restSeconds: 60, orderIndex: 5 },
  ],
  "Bodyweight Basics": [
    { name: "Push-Up", sets: 3, reps: 12, restSeconds: 60, orderIndex: 0 },
    { name: "Pull-Up", sets: 3, reps: 6, restSeconds: 90, orderIndex: 1 },
    { name: "Goblet Squat", sets: 3, reps: 15, restSeconds: 60, orderIndex: 2 },
    { name: "Plank", sets: 3, reps: 30, restSeconds: 45, orderIndex: 3 },
    { name: "Burpee", sets: 3, reps: 8, restSeconds: 60, orderIndex: 4 },
    { name: "Mountain Climbers", sets: 3, reps: 20, restSeconds: 45, orderIndex: 5 },
  ],
  "Dumbbell Only Beginner": [
    { name: "Dumbbell Bench Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 0 },
    { name: "One-Arm Dumbbell Row", sets: 3, reps: 10, restSeconds: 90, orderIndex: 1 },
    { name: "Seated Dumbbell Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Goblet Squat", sets: 3, reps: 12, restSeconds: 90, orderIndex: 3 },
    { name: "Dumbbell Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Overhead Tricep Extension", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
  ],
  "Morning Mobility Flow": [
    { name: "Cat-Cow", sets: 2, reps: 10, restSeconds: 30, orderIndex: 0 },
    { name: "World's Greatest Stretch", sets: 2, reps: 5, restSeconds: 30, orderIndex: 1 },
    { name: "Hip Flexor Stretch", sets: 2, reps: 30, restSeconds: 30, orderIndex: 2 },
    { name: "Thoracic Extension", sets: 2, reps: 10, restSeconds: 30, orderIndex: 3 },
    { name: "Pigeon Pose", sets: 2, reps: 30, restSeconds: 30, orderIndex: 4 },
  ],
  "Beginner Cardio Conditioning": [
    { name: "Treadmill Run", sets: 1, reps: 15, restSeconds: 60, orderIndex: 0 },
    { name: "Rowing Machine", sets: 3, reps: 5, restSeconds: 60, orderIndex: 1 },
    { name: "Jump Rope", sets: 3, reps: 60, restSeconds: 60, orderIndex: 2 },
    { name: "Stationary Bike", sets: 1, reps: 10, restSeconds: 60, orderIndex: 3 },
  ],
  "First Week Strength": [
    { name: "Barbell Back Squat", sets: 3, reps: 5, restSeconds: 120, orderIndex: 0 },
    { name: "Barbell Bench Press", sets: 3, reps: 5, restSeconds: 120, orderIndex: 1 },
    { name: "Deadlift", sets: 1, reps: 5, restSeconds: 180, orderIndex: 2 },
    { name: "Barbell Row", sets: 3, reps: 5, restSeconds: 90, orderIndex: 3 },
  ],
  "Core Foundations": [
    { name: "Plank", sets: 3, reps: 30, restSeconds: 45, orderIndex: 0 },
    { name: "Side Plank", sets: 2, reps: 20, restSeconds: 45, orderIndex: 1 },
    { name: "Crunches", sets: 3, reps: 15, restSeconds: 45, orderIndex: 2 },
    { name: "Bicycle Crunch", sets: 3, reps: 20, restSeconds: 45, orderIndex: 3 },
    { name: "Dead Bug", sets: 3, reps: 8, restSeconds: 60, orderIndex: 4 },
    { name: "Leg Raise", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
  ],
  "Upper Body A": [
    { name: "Barbell Bench Press", sets: 4, reps: 8, restSeconds: 120, orderIndex: 0 },
    { name: "Barbell Row", sets: 4, reps: 8, restSeconds: 120, orderIndex: 1 },
    { name: "Overhead Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Lat Pulldown", sets: 3, reps: 10, restSeconds: 90, orderIndex: 3 },
    { name: "Barbell Curl", sets: 3, reps: 10, restSeconds: 60, orderIndex: 4 },
    { name: "Tricep Pushdown", sets: 3, reps: 10, restSeconds: 60, orderIndex: 5 },
  ],
  "Upper Body B": [
    { name: "Incline Barbell Press", sets: 4, reps: 8, restSeconds: 120, orderIndex: 0 },
    { name: "Pull-Up", sets: 4, reps: 6, restSeconds: 120, orderIndex: 1 },
    { name: "Seated Dumbbell Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Seated Cable Row", sets: 3, reps: 10, restSeconds: 90, orderIndex: 3 },
    { name: "EZ Bar Curl", sets: 3, reps: 10, restSeconds: 60, orderIndex: 4 },
    { name: "Skull Crusher", sets: 3, reps: 10, restSeconds: 60, orderIndex: 5 },
  ],
  "Lower Body A": [
    { name: "Barbell Back Squat", sets: 4, reps: 6, restSeconds: 180, orderIndex: 0 },
    { name: "Leg Press", sets: 3, reps: 12, restSeconds: 120, orderIndex: 1 },
    { name: "Bulgarian Split Squat", sets: 3, reps: 8, restSeconds: 90, orderIndex: 2 },
    { name: "Leg Extension", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Standing Calf Raise", sets: 4, reps: 15, restSeconds: 60, orderIndex: 4 },
  ],
  "Lower Body B": [
    { name: "Deadlift", sets: 4, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Romanian Deadlift", sets: 3, reps: 10, restSeconds: 120, orderIndex: 1 },
    { name: "Lying Leg Curl", sets: 3, reps: 12, restSeconds: 90, orderIndex: 2 },
    { name: "Hip Thrust", sets: 3, reps: 12, restSeconds: 90, orderIndex: 3 },
    { name: "Seated Calf Raise", sets: 4, reps: 15, restSeconds: 60, orderIndex: 4 },
  ],
  "Push Day": [
    { name: "Barbell Bench Press", sets: 4, reps: 8, restSeconds: 120, orderIndex: 0 },
    { name: "Incline Barbell Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 1 },
    { name: "Overhead Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Lateral Raise", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Tricep Pushdown", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Dumbbell Flye", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
  ],
  "Pull Day": [
    { name: "Deadlift", sets: 3, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Barbell Row", sets: 4, reps: 8, restSeconds: 120, orderIndex: 1 },
    { name: "Lat Pulldown", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Face Pull", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Barbell Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Hammer Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
  ],
  "Leg Day": [
    { name: "Barbell Back Squat", sets: 4, reps: 8, restSeconds: 180, orderIndex: 0 },
    { name: "Romanian Deadlift", sets: 3, reps: 10, restSeconds: 120, orderIndex: 1 },
    { name: "Leg Press", sets: 3, reps: 12, restSeconds: 120, orderIndex: 2 },
    { name: "Leg Extension", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Lying Leg Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Standing Calf Raise", sets: 4, reps: 15, restSeconds: 60, orderIndex: 5 },
  ],
  "Active Recovery": [
    { name: "Hip Flexor Stretch", sets: 2, reps: 30, restSeconds: 30, orderIndex: 0 },
    { name: "World's Greatest Stretch", sets: 2, reps: 5, restSeconds: 30, orderIndex: 1 },
    { name: "Cat-Cow", sets: 2, reps: 10, restSeconds: 30, orderIndex: 2 },
    { name: "Pigeon Pose", sets: 2, reps: 30, restSeconds: 30, orderIndex: 3 },
    { name: "Thoracic Extension", sets: 2, reps: 10, restSeconds: 30, orderIndex: 4 },
  ],
  "Chest & Triceps Hypertrophy": [
    { name: "Barbell Bench Press", sets: 4, reps: 10, restSeconds: 90, orderIndex: 0 },
    { name: "Incline Dumbbell Press", sets: 3, reps: 12, restSeconds: 90, orderIndex: 1 },
    { name: "Cable Flye", sets: 3, reps: 15, restSeconds: 60, orderIndex: 2 },
    { name: "Dumbbell Flye", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Tricep Pushdown", sets: 4, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Skull Crusher", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
    { name: "Overhead Tricep Extension", sets: 3, reps: 15, restSeconds: 60, orderIndex: 6 },
  ],
  "Back & Biceps Hypertrophy": [
    { name: "Deadlift", sets: 3, reps: 6, restSeconds: 180, orderIndex: 0 },
    { name: "Barbell Row", sets: 4, reps: 10, restSeconds: 90, orderIndex: 1 },
    { name: "Lat Pulldown", sets: 3, reps: 12, restSeconds: 90, orderIndex: 2 },
    { name: "Seated Cable Row", sets: 3, reps: 12, restSeconds: 90, orderIndex: 3 },
    { name: "Face Pull", sets: 3, reps: 15, restSeconds: 60, orderIndex: 4 },
    { name: "Barbell Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
    { name: "Hammer Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 6 },
  ],
  "Shoulder Hypertrophy": [
    { name: "Overhead Press", sets: 4, reps: 10, restSeconds: 90, orderIndex: 0 },
    { name: "Lateral Raise", sets: 4, reps: 15, restSeconds: 60, orderIndex: 1 },
    { name: "Cable Lateral Raise", sets: 3, reps: 15, restSeconds: 60, orderIndex: 2 },
    { name: "Front Raise", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Rear Delt Flye", sets: 3, reps: 15, restSeconds: 60, orderIndex: 4 },
    { name: "Arnold Press", sets: 3, reps: 12, restSeconds: 90, orderIndex: 5 },
    { name: "Barbell Shrug", sets: 3, reps: 15, restSeconds: 60, orderIndex: 6 },
  ],
  "Legs Hypertrophy": [
    { name: "Barbell Back Squat", sets: 4, reps: 10, restSeconds: 120, orderIndex: 0 },
    { name: "Leg Press", sets: 4, reps: 15, restSeconds: 90, orderIndex: 1 },
    { name: "Romanian Deadlift", sets: 3, reps: 12, restSeconds: 90, orderIndex: 2 },
    { name: "Leg Extension", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Lying Leg Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Hip Thrust", sets: 3, reps: 12, restSeconds: 90, orderIndex: 5 },
    { name: "Standing Calf Raise", sets: 4, reps: 20, restSeconds: 60, orderIndex: 6 },
  ],
  "Arm Specialization": [
    { name: "Barbell Curl", sets: 4, reps: 10, restSeconds: 90, orderIndex: 0 },
    { name: "EZ Bar Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 1 },
    { name: "Hammer Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 2 },
    { name: "Concentration Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Close Grip Bench Press", sets: 4, reps: 10, restSeconds: 90, orderIndex: 4 },
    { name: "Tricep Pushdown", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
    { name: "Skull Crusher", sets: 3, reps: 12, restSeconds: 60, orderIndex: 6 },
  ],
  "Chest Specialization": [
    { name: "Barbell Bench Press", sets: 5, reps: 8, restSeconds: 120, orderIndex: 0 },
    { name: "Incline Barbell Press", sets: 4, reps: 10, restSeconds: 90, orderIndex: 1 },
    { name: "Decline Barbell Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Cable Flye", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Dumbbell Flye", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Pec Deck Machine", sets: 3, reps: 15, restSeconds: 60, orderIndex: 5 },
  ],
  "Back Specialization": [
    { name: "Deadlift", sets: 4, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Barbell Row", sets: 4, reps: 8, restSeconds: 120, orderIndex: 1 },
    { name: "T-Bar Row", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Lat Pulldown", sets: 3, reps: 12, restSeconds: 90, orderIndex: 3 },
    { name: "Seated Cable Row", sets: 3, reps: 12, restSeconds: 90, orderIndex: 4 },
    { name: "One-Arm Dumbbell Row", sets: 3, reps: 10, restSeconds: 90, orderIndex: 5 },
    { name: "Cable Straight-Arm Pulldown", sets: 3, reps: 15, restSeconds: 60, orderIndex: 6 },
  ],
  "Glute Focus": [
    { name: "Hip Thrust", sets: 4, reps: 12, restSeconds: 90, orderIndex: 0 },
    { name: "Bulgarian Split Squat", sets: 3, reps: 10, restSeconds: 90, orderIndex: 1 },
    { name: "Sumo Squat", sets: 3, reps: 12, restSeconds: 90, orderIndex: 2 },
    { name: "Romanian Deadlift", sets: 3, reps: 10, restSeconds: 90, orderIndex: 3 },
    { name: "Lying Leg Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Seated Calf Raise", sets: 3, reps: 15, restSeconds: 60, orderIndex: 5 },
  ],
  "Squat Day (Strength)": [
    { name: "Barbell Back Squat", sets: 5, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Front Squat", sets: 3, reps: 4, restSeconds: 180, orderIndex: 1 },
    { name: "Leg Press", sets: 3, reps: 10, restSeconds: 120, orderIndex: 2 },
    { name: "Romanian Deadlift", sets: 3, reps: 8, restSeconds: 90, orderIndex: 3 },
    { name: "Leg Extension", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
  ],
  "Bench Day (Strength)": [
    { name: "Barbell Bench Press", sets: 5, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Incline Barbell Press", sets: 3, reps: 6, restSeconds: 120, orderIndex: 1 },
    { name: "Close Grip Bench Press", sets: 3, reps: 8, restSeconds: 90, orderIndex: 2 },
    { name: "Tricep Pushdown", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Skull Crusher", sets: 3, reps: 10, restSeconds: 60, orderIndex: 4 },
  ],
  "Deadlift Day (Strength)": [
    { name: "Deadlift", sets: 5, reps: 5, restSeconds: 240, orderIndex: 0 },
    { name: "Rack Pull", sets: 3, reps: 4, restSeconds: 180, orderIndex: 1 },
    { name: "Romanian Deadlift", sets: 3, reps: 8, restSeconds: 120, orderIndex: 2 },
    { name: "Barbell Row", sets: 3, reps: 8, restSeconds: 90, orderIndex: 3 },
    { name: "Face Pull", sets: 3, reps: 15, restSeconds: 60, orderIndex: 4 },
  ],
  "OHP Day (Strength)": [
    { name: "Overhead Press", sets: 5, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Lateral Raise", sets: 4, reps: 12, restSeconds: 60, orderIndex: 1 },
    { name: "Arnold Press", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Barbell Shrug", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Face Pull", sets: 3, reps: 15, restSeconds: 60, orderIndex: 4 },
  ],
  "5x5 Workout A": [
    { name: "Barbell Back Squat", sets: 5, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Barbell Bench Press", sets: 5, reps: 5, restSeconds: 180, orderIndex: 1 },
    { name: "Barbell Row", sets: 5, reps: 5, restSeconds: 180, orderIndex: 2 },
  ],
  "5x5 Workout B": [
    { name: "Barbell Back Squat", sets: 5, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Overhead Press", sets: 5, reps: 5, restSeconds: 180, orderIndex: 1 },
    { name: "Deadlift", sets: 1, reps: 5, restSeconds: 300, orderIndex: 2 },
  ],
  "Heavy Singles Day": [
    { name: "Barbell Back Squat", sets: 3, reps: 1, restSeconds: 300, orderIndex: 0 },
    { name: "Barbell Bench Press", sets: 3, reps: 1, restSeconds: 300, orderIndex: 1 },
    { name: "Deadlift", sets: 3, reps: 1, restSeconds: 300, orderIndex: 2 },
  ],
  "Deload Week Workout": [
    { name: "Barbell Back Squat", sets: 2, reps: 8, restSeconds: 90, orderIndex: 0 },
    { name: "Barbell Bench Press", sets: 2, reps: 8, restSeconds: 90, orderIndex: 1 },
    { name: "Barbell Row", sets: 2, reps: 8, restSeconds: 90, orderIndex: 2 },
    { name: "Deadlift", sets: 2, reps: 5, restSeconds: 120, orderIndex: 3 },
  ],
  "HIIT Circuit A": [
    { name: "Burpee", sets: 4, reps: 10, restSeconds: 30, orderIndex: 0 },
    { name: "Box Jump", sets: 4, reps: 8, restSeconds: 30, orderIndex: 1 },
    { name: "Kettlebell Swing", sets: 4, reps: 15, restSeconds: 30, orderIndex: 2 },
    { name: "Battle Rope Waves", sets: 4, reps: 20, restSeconds: 30, orderIndex: 3 },
    { name: "Mountain Climbers", sets: 4, reps: 20, restSeconds: 30, orderIndex: 4 },
  ],
  "HIIT Circuit B": [
    { name: "Thruster", sets: 4, reps: 10, restSeconds: 30, orderIndex: 0 },
    { name: "Burpee", sets: 4, reps: 8, restSeconds: 30, orderIndex: 1 },
    { name: "Kettlebell Swing", sets: 4, reps: 15, restSeconds: 30, orderIndex: 2 },
    { name: "Jump Rope", sets: 4, reps: 50, restSeconds: 30, orderIndex: 3 },
    { name: "Sled Push", sets: 4, reps: 1, restSeconds: 60, orderIndex: 4 },
  ],
  "Athletic Power Development": [
    { name: "Box Jump", sets: 4, reps: 5, restSeconds: 90, orderIndex: 0 },
    { name: "Power Clean", sets: 4, reps: 4, restSeconds: 120, orderIndex: 1 },
    { name: "Thruster", sets: 3, reps: 6, restSeconds: 90, orderIndex: 2 },
    { name: "Bulgarian Split Squat", sets: 3, reps: 8, restSeconds: 90, orderIndex: 3 },
  ],
  "Kettlebell Conditioning": [
    { name: "Kettlebell Swing", sets: 4, reps: 20, restSeconds: 60, orderIndex: 0 },
    { name: "Kettlebell Clean", sets: 3, reps: 10, restSeconds: 60, orderIndex: 1 },
    { name: "Turkish Get-Up", sets: 3, reps: 3, restSeconds: 90, orderIndex: 2 },
    { name: "Goblet Squat", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
  ],
  "Sprint Intervals": [
    { name: "Treadmill Run", sets: 8, reps: 1, restSeconds: 90, orderIndex: 0 },
    { name: "Assault Bike", sets: 4, reps: 1, restSeconds: 120, orderIndex: 1 },
    { name: "Stair Climber", sets: 3, reps: 1, restSeconds: 90, orderIndex: 2 },
  ],
  "Functional Fitness": [
    { name: "Thruster", sets: 3, reps: 10, restSeconds: 90, orderIndex: 0 },
    { name: "Kettlebell Swing", sets: 3, reps: 15, restSeconds: 60, orderIndex: 1 },
    { name: "Pull-Up", sets: 3, reps: 8, restSeconds: 90, orderIndex: 2 },
    { name: "Push-Up", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Barbell Row", sets: 3, reps: 10, restSeconds: 90, orderIndex: 4 },
  ],
  "CrossFit-Style WOD": [
    { name: "Barbell Back Squat", sets: 3, reps: 10, restSeconds: 60, orderIndex: 0 },
    { name: "Pull-Up", sets: 3, reps: 8, restSeconds: 60, orderIndex: 1 },
    { name: "Push-Up", sets: 3, reps: 15, restSeconds: 60, orderIndex: 2 },
    { name: "Kettlebell Swing", sets: 3, reps: 20, restSeconds: 60, orderIndex: 3 },
    { name: "Burpee", sets: 3, reps: 10, restSeconds: 60, orderIndex: 4 },
  ],
  "Advanced Push Day": [
    { name: "Barbell Bench Press", sets: 5, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Incline Barbell Press", sets: 4, reps: 8, restSeconds: 120, orderIndex: 1 },
    { name: "Overhead Press", sets: 4, reps: 8, restSeconds: 120, orderIndex: 2 },
    { name: "Lateral Raise", sets: 4, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Tricep Pushdown", sets: 4, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Dumbbell Flye", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
    { name: "Arnold Press", sets: 3, reps: 12, restSeconds: 60, orderIndex: 6 },
  ],
  "Advanced Pull Day": [
    { name: "Deadlift", sets: 4, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Barbell Row", sets: 4, reps: 8, restSeconds: 120, orderIndex: 1 },
    { name: "Pull-Up", sets: 4, reps: 8, restSeconds: 90, orderIndex: 2 },
    { name: "Lat Pulldown", sets: 3, reps: 10, restSeconds: 90, orderIndex: 3 },
    { name: "Face Pull", sets: 3, reps: 15, restSeconds: 60, orderIndex: 4 },
    { name: "Barbell Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
    { name: "One-Arm Dumbbell Row", sets: 3, reps: 10, restSeconds: 90, orderIndex: 6 },
  ],
  "Advanced Leg Day": [
    { name: "Barbell Back Squat", sets: 5, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "Romanian Deadlift", sets: 4, reps: 8, restSeconds: 120, orderIndex: 1 },
    { name: "Hack Squat", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Leg Press", sets: 3, reps: 12, restSeconds: 90, orderIndex: 3 },
    { name: "Walking Lunge", sets: 3, reps: 12, restSeconds: 90, orderIndex: 4 },
    { name: "Nordic Curl", sets: 3, reps: 5, restSeconds: 90, orderIndex: 5 },
    { name: "Standing Calf Raise", sets: 4, reps: 20, restSeconds: 60, orderIndex: 6 },
  ],
  "Olympic Lifting Session": [
    { name: "Power Clean", sets: 5, reps: 3, restSeconds: 180, orderIndex: 0 },
    { name: "Thruster", sets: 4, reps: 5, restSeconds: 120, orderIndex: 1 },
    { name: "Overhead Press", sets: 3, reps: 5, restSeconds: 90, orderIndex: 2 },
    { name: "Front Squat", sets: 3, reps: 5, restSeconds: 120, orderIndex: 3 },
  ],
  "Bodybuilding Chest Day": [
    { name: "Barbell Bench Press", sets: 4, reps: 8, restSeconds: 120, orderIndex: 0 },
    { name: "Incline Dumbbell Press", sets: 4, reps: 10, restSeconds: 90, orderIndex: 1 },
    { name: "Cable Flye", sets: 3, reps: 15, restSeconds: 60, orderIndex: 2 },
    { name: "Pec Deck Machine", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
    { name: "Chest Dip", sets: 3, reps: 10, restSeconds: 60, orderIndex: 4 },
    { name: "Hex Press", sets: 3, reps: 12, restSeconds: 60, orderIndex: 5 },
  ],
  "Mass Building Back Day": [
    { name: "Deadlift", sets: 4, reps: 5, restSeconds: 180, orderIndex: 0 },
    { name: "T-Bar Row", sets: 4, reps: 8, restSeconds: 120, orderIndex: 1 },
    { name: "Lat Pulldown", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Seated Cable Row", sets: 3, reps: 12, restSeconds: 90, orderIndex: 3 },
    { name: "One-Arm Dumbbell Row", sets: 3, reps: 10, restSeconds: 90, orderIndex: 4 },
    { name: "Cable Straight-Arm Pulldown", sets: 3, reps: 15, restSeconds: 60, orderIndex: 5 },
  ],
  "Advanced Core & Abs": [
    { name: "Cable Crunch", sets: 4, reps: 15, restSeconds: 60, orderIndex: 0 },
    { name: "Ab Wheel Rollout", sets: 3, reps: 10, restSeconds: 60, orderIndex: 1 },
    { name: "Leg Raise", sets: 3, reps: 15, restSeconds: 60, orderIndex: 2 },
    { name: "Russian Twist", sets: 3, reps: 20, restSeconds: 60, orderIndex: 3 },
    { name: "Pallof Press", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
    { name: "Dragon Flag", sets: 3, reps: 5, restSeconds: 90, orderIndex: 5 },
  ],
  "Peak Week Pump Session": [
    { name: "Barbell Bench Press", sets: 3, reps: 15, restSeconds: 60, orderIndex: 0 },
    { name: "Lat Pulldown", sets: 3, reps: 15, restSeconds: 60, orderIndex: 1 },
    { name: "Lateral Raise", sets: 4, reps: 20, restSeconds: 45, orderIndex: 2 },
    { name: "Barbell Curl", sets: 3, reps: 15, restSeconds: 45, orderIndex: 3 },
    { name: "Tricep Pushdown", sets: 3, reps: 15, restSeconds: 45, orderIndex: 4 },
    { name: "Leg Extension", sets: 3, reps: 20, restSeconds: 45, orderIndex: 5 },
  ],
  "Mobility & Stretching": [
    { name: "World's Greatest Stretch", sets: 3, reps: 5, restSeconds: 30, orderIndex: 0 },
    { name: "Hip Flexor Stretch", sets: 3, reps: 30, restSeconds: 30, orderIndex: 1 },
    { name: "Pigeon Pose", sets: 3, reps: 30, restSeconds: 30, orderIndex: 2 },
    { name: "Cat-Cow", sets: 3, reps: 10, restSeconds: 30, orderIndex: 3 },
    { name: "Thoracic Extension", sets: 3, reps: 10, restSeconds: 30, orderIndex: 4 },
  ],
  "Posterior Chain Focus": [
    { name: "Deadlift", sets: 4, reps: 6, restSeconds: 180, orderIndex: 0 },
    { name: "Romanian Deadlift", sets: 3, reps: 10, restSeconds: 120, orderIndex: 1 },
    { name: "Good Morning", sets: 3, reps: 10, restSeconds: 90, orderIndex: 2 },
    { name: "Lying Leg Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Barbell Row", sets: 3, reps: 8, restSeconds: 90, orderIndex: 4 },
  ],
  "Core Stability Advanced": [
    { name: "Plank", sets: 4, reps: 60, restSeconds: 45, orderIndex: 0 },
    { name: "Side Plank", sets: 3, reps: 45, restSeconds: 45, orderIndex: 1 },
    { name: "Pallof Press", sets: 3, reps: 12, restSeconds: 60, orderIndex: 2 },
    { name: "Ab Wheel Rollout", sets: 3, reps: 10, restSeconds: 60, orderIndex: 3 },
    { name: "Dead Bug", sets: 3, reps: 10, restSeconds: 60, orderIndex: 4 },
    { name: "Hollow Body Hold", sets: 3, reps: 30, restSeconds: 60, orderIndex: 5 },
  ],
  "Shoulder Rehab & Prehab": [
    { name: "Face Pull", sets: 4, reps: 15, restSeconds: 60, orderIndex: 0 },
    { name: "Cable Lateral Raise", sets: 3, reps: 15, restSeconds: 60, orderIndex: 1 },
    { name: "Rear Delt Flye", sets: 3, reps: 15, restSeconds: 60, orderIndex: 2 },
    { name: "Cable Face Pull", sets: 3, reps: 15, restSeconds: 60, orderIndex: 3 },
  ],
  "Grip & Forearm Strength": [
    { name: "Deadlift", sets: 3, reps: 5, restSeconds: 120, orderIndex: 0 },
    { name: "Barbell Row", sets: 3, reps: 8, restSeconds: 90, orderIndex: 1 },
    { name: "Barbell Curl", sets: 3, reps: 10, restSeconds: 60, orderIndex: 2 },
    { name: "Reverse Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 3 },
    { name: "Hammer Curl", sets: 3, reps: 12, restSeconds: 60, orderIndex: 4 },
  ],
  "Mindful Yoga Flow": [
    { name: "World's Greatest Stretch", sets: 3, reps: 5, restSeconds: 30, orderIndex: 0 },
    { name: "Pigeon Pose", sets: 3, reps: 30, restSeconds: 30, orderIndex: 1 },
    { name: "Cat-Cow", sets: 3, reps: 10, restSeconds: 30, orderIndex: 2 },
    { name: "Hip Flexor Stretch", sets: 3, reps: 30, restSeconds: 30, orderIndex: 3 },
  ],
  "Boxing Conditioning": [
    { name: "Burpee", sets: 4, reps: 10, restSeconds: 45, orderIndex: 0 },
    { name: "Jump Rope", sets: 5, reps: 60, restSeconds: 30, orderIndex: 1 },
    { name: "Mountain Climbers", sets: 4, reps: 20, restSeconds: 30, orderIndex: 2 },
    { name: "Battle Rope Waves", sets: 4, reps: 30, restSeconds: 45, orderIndex: 3 },
  ],
};

async function main() {
  console.log("🌱 Clearing old workout exercises and logs...");
  await db.execute(sql`TRUNCATE TABLE workout_exercises CASCADE`);
  await db.execute(sql`DELETE FROM exercises WHERE is_custom = false`);

  console.log("🌱 Seeding exercises...");
  for (const e of exercises) {
    await db.insert(exercisesTable).values({
      name: e.name,
      description: e.description,
      category: e.category,
      muscleGroup: e.muscleGroup,
      equipment: e.equipment,
      instructions: (e as { instructions?: string }).instructions ?? null,
      isCustom: false,
    }).onConflictDoNothing();
  }
  console.log(`✅ ${exercises.length} exercises seeded`);

  // Build name → id map
  const allExercises = await db.select({ id: exercisesTable.id, name: exercisesTable.name }).from(exercisesTable);
  const exerciseByName = new Map(allExercises.map(e => [e.name, e.id]));

  console.log("🌱 Seeding workout plans...");
  // Re-insert workouts fresh
  await db.execute(sql`DELETE FROM workouts WHERE user_id IS NULL`);

  const workoutDefs = [
    { name: "Full Body Starter A", description: "Beginner full-body workout for foundational strength.", difficulty: "beginner", estimatedMinutes: 45, category: "strength" },
    { name: "Full Body Starter B", description: "Alternate with Starter A for a 3-day/week program.", difficulty: "beginner", estimatedMinutes: 45, category: "strength" },
    { name: "Bodyweight Basics", description: "No equipment needed. Perfect for beginners at home.", difficulty: "beginner", estimatedMinutes: 30, category: "bodyweight" },
    { name: "Dumbbell Only Beginner", description: "Full body workout using only a pair of dumbbells.", difficulty: "beginner", estimatedMinutes: 40, category: "strength" },
    { name: "Morning Mobility Flow", description: "Gentle 30-minute mobility and flexibility routine.", difficulty: "beginner", estimatedMinutes: 30, category: "mobility" },
    { name: "Beginner Cardio Conditioning", description: "Low intensity cardio intervals for base conditioning.", difficulty: "beginner", estimatedMinutes: 30, category: "cardio" },
    { name: "First Week Strength", description: "Simple intro to compound movements for week 1.", difficulty: "beginner", estimatedMinutes: 40, category: "strength" },
    { name: "Core Foundations", description: "Build a solid core foundation with beginner-friendly moves.", difficulty: "beginner", estimatedMinutes: 25, category: "core" },
    { name: "Upper Body A", description: "Horizontal push/pull emphasis for upper body.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
    { name: "Upper Body B", description: "Vertical push/pull emphasis for upper body.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
    { name: "Lower Body A", description: "Squat-pattern dominant lower body session.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
    { name: "Lower Body B", description: "Hinge-pattern dominant lower body session.", difficulty: "intermediate", estimatedMinutes: 55, category: "strength" },
    { name: "Push Day", description: "Chest, shoulders, and triceps compound and isolation work.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
    { name: "Pull Day", description: "Back, biceps, and rear delts compound and isolation work.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
    { name: "Leg Day", description: "Quad, hamstring, glute, and calf comprehensive session.", difficulty: "intermediate", estimatedMinutes: 65, category: "strength" },
    { name: "Active Recovery", description: "Light movement, foam rolling, and mobility work.", difficulty: "beginner", estimatedMinutes: 30, category: "mobility" },
    { name: "Chest & Triceps Hypertrophy", description: "Volume-focused push session for muscle size.", difficulty: "intermediate", estimatedMinutes: 65, category: "hypertrophy" },
    { name: "Back & Biceps Hypertrophy", description: "High volume pulling session for back width and thickness.", difficulty: "intermediate", estimatedMinutes: 65, category: "hypertrophy" },
    { name: "Shoulder Hypertrophy", description: "All three delt heads with lateral raises and presses.", difficulty: "intermediate", estimatedMinutes: 50, category: "hypertrophy" },
    { name: "Legs Hypertrophy", description: "High volume quad and hamstring session.", difficulty: "intermediate", estimatedMinutes: 70, category: "hypertrophy" },
    { name: "Arm Specialization", description: "Dedicated bicep and tricep volume day.", difficulty: "intermediate", estimatedMinutes: 45, category: "hypertrophy" },
    { name: "Chest Specialization", description: "High volume chest with multiple angles and tempos.", difficulty: "intermediate", estimatedMinutes: 60, category: "hypertrophy" },
    { name: "Back Specialization", description: "Thickness and width focus with heavy rows and pulldowns.", difficulty: "intermediate", estimatedMinutes: 60, category: "hypertrophy" },
    { name: "Glute Focus", description: "Glute-dominant lower body session.", difficulty: "intermediate", estimatedMinutes: 55, category: "hypertrophy" },
    { name: "Squat Day (Strength)", description: "Squat-focused strength session with accessory work.", difficulty: "advanced", estimatedMinutes: 75, category: "powerlifting" },
    { name: "Bench Day (Strength)", description: "Bench press-focused session with tricep accessories.", difficulty: "advanced", estimatedMinutes: 70, category: "powerlifting" },
    { name: "Deadlift Day (Strength)", description: "Deadlift main lift with back accessories.", difficulty: "advanced", estimatedMinutes: 70, category: "powerlifting" },
    { name: "OHP Day (Strength)", description: "Overhead press as main movement.", difficulty: "advanced", estimatedMinutes: 65, category: "powerlifting" },
    { name: "5x5 Workout A", description: "StrongLifts 5x5 Workout A pattern.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
    { name: "5x5 Workout B", description: "StrongLifts 5x5 Workout B pattern.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
    { name: "Heavy Singles Day", description: "Max effort day working up to heavy singles.", difficulty: "advanced", estimatedMinutes: 80, category: "powerlifting" },
    { name: "Deload Week Workout", description: "Reduced intensity for recovery and adaptation.", difficulty: "beginner", estimatedMinutes: 40, category: "strength" },
    { name: "HIIT Circuit A", description: "High intensity interval training with bodyweight and kettlebells.", difficulty: "intermediate", estimatedMinutes: 35, category: "cardio" },
    { name: "HIIT Circuit B", description: "Metabolic conditioning circuit for fat loss.", difficulty: "intermediate", estimatedMinutes: 35, category: "cardio" },
    { name: "Athletic Power Development", description: "Box jumps, cleans, and explosive movements.", difficulty: "advanced", estimatedMinutes: 60, category: "athletic" },
    { name: "Kettlebell Conditioning", description: "Swings, cleans, snatches for full body conditioning.", difficulty: "intermediate", estimatedMinutes: 45, category: "conditioning" },
    { name: "Sprint Intervals", description: "Treadmill sprint intervals for speed and conditioning.", difficulty: "advanced", estimatedMinutes: 30, category: "cardio" },
    { name: "Functional Fitness", description: "Compound movements mimicking real-world patterns.", difficulty: "intermediate", estimatedMinutes: 50, category: "functional" },
    { name: "CrossFit-Style WOD", description: "Mixed modal workout combining strength and cardio.", difficulty: "advanced", estimatedMinutes: 40, category: "conditioning" },
    { name: "Advanced Push Day", description: "High-frequency heavy push with intensity techniques.", difficulty: "advanced", estimatedMinutes: 75, category: "strength" },
    { name: "Advanced Pull Day", description: "Heavy rowing and pulling with accessory volume.", difficulty: "advanced", estimatedMinutes: 75, category: "strength" },
    { name: "Advanced Leg Day", description: "Squat, hinge, and single-leg work at high intensity.", difficulty: "advanced", estimatedMinutes: 80, category: "strength" },
    { name: "Olympic Lifting Session", description: "Power clean and overhead work.", difficulty: "advanced", estimatedMinutes: 75, category: "olympic" },
    { name: "Bodybuilding Chest Day", description: "Pre-exhaust techniques and high rep finishers.", difficulty: "advanced", estimatedMinutes: 70, category: "hypertrophy" },
    { name: "Mass Building Back Day", description: "Deadlifts, rows, and pulldowns for maximum back mass.", difficulty: "advanced", estimatedMinutes: 75, category: "hypertrophy" },
    { name: "Advanced Core & Abs", description: "Weighted core work, planks, and rotational strength.", difficulty: "advanced", estimatedMinutes: 40, category: "core" },
    { name: "Peak Week Pump Session", description: "Light weight, high rep pump work.", difficulty: "intermediate", estimatedMinutes: 50, category: "hypertrophy" },
    { name: "Mobility & Stretching", description: "Comprehensive flexibility and mobility session.", difficulty: "beginner", estimatedMinutes: 60, category: "mobility" },
    { name: "Posterior Chain Focus", description: "Deadlift, RDL, hamstring curls, and back extensions.", difficulty: "intermediate", estimatedMinutes: 60, category: "strength" },
    { name: "Core Stability Advanced", description: "Anti-rotation, anti-flexion, and stability challenges.", difficulty: "advanced", estimatedMinutes: 40, category: "core" },
    { name: "Shoulder Rehab & Prehab", description: "Rotator cuff strengthening and mobility.", difficulty: "beginner", estimatedMinutes: 30, category: "mobility" },
    { name: "Grip & Forearm Strength", description: "Wrist curls, farmer's carries, and plate pinches.", difficulty: "intermediate", estimatedMinutes: 25, category: "strength" },
    { name: "Mindful Yoga Flow", description: "Strength yoga blending flexibility with bodyweight resistance.", difficulty: "beginner", estimatedMinutes: 45, category: "yoga" },
    { name: "Boxing Conditioning", description: "Shadow boxing, bag work, and footwork drills.", difficulty: "intermediate", estimatedMinutes: 45, category: "cardio" },
  ];

  for (const w of workoutDefs) {
    await db.insert(workoutsTable).values({
      name: w.name,
      description: w.description,
      difficulty: w.difficulty,
      estimatedMinutes: w.estimatedMinutes,
      category: w.category,
      isAiGenerated: false,
    });
  }
  console.log(`✅ ${workoutDefs.length} workout plans seeded`);

  // Fetch inserted workouts
  const allWorkouts = await db.select({ id: workoutsTable.id, name: workoutsTable.name })
    .from(workoutsTable)
    .where(sql`user_id IS NULL`);
  const workoutByName = new Map(allWorkouts.map(w => [w.name, w.id]));

  console.log("🌱 Seeding workout exercises...");
  let totalExercises = 0;
  for (const [workoutName, exDefs] of Object.entries(workoutExerciseMap)) {
    const workoutId = workoutByName.get(workoutName);
    if (!workoutId) { console.warn(`  ⚠ Workout not found: ${workoutName}`); continue; }
    for (const exDef of exDefs) {
      const exerciseId = exerciseByName.get(exDef.name);
      if (!exerciseId) { console.warn(`  ⚠ Exercise not found: ${exDef.name}`); continue; }
      await db.insert(workoutExercisesTable).values({
        workoutId,
        exerciseId,
        sets: exDef.sets,
        reps: exDef.reps,
        restSeconds: exDef.restSeconds,
        orderIndex: exDef.orderIndex,
      });
      totalExercises++;
    }
  }
  console.log(`✅ ${totalExercises} workout exercises seeded`);

  await pool.end();
  console.log("🎉 Seed complete!");
}

main().catch((e) => { console.error(e); process.exit(1); });
